title: Quaner's Blog
author:
  name: quaner
  email: 217quaner@gmail.com
description:  Quaner's Blog

show_excerpts: false

minima:
  date_format: "%b %-d, %Y"

theme: minima

plugins:
 - jekyll-paginate