title: Quaner's Blog
author:
  name: quaner
  email: 217quaner@gmail.com
description:  Quaner's Blog

show_excerpts: false

# Minima date format
minima:
  date_format: "%b %-d, %Y"

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
