title: Quaner
author:
  name: quaner
  email: 217quaner@gmail.com
description: Blog

show_excerpts: false

minima:
  date_format: "%b %-d, %Y"

theme: minima

plugins:
 - jekyll-paginate

paginate: 5
